Myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls','cart'),namespace='cart')),
    path('orders/', include(('orders.urls','orders'),namespace='orders')),
     path('payement/', include(('payement.urls','payement'),namespace='payement')),
     path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
    path('', include(('shop.urls','shop'),namespace='shop')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .forms import LoginForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name="accounts"
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html",redirect_authenticated_user=True,authentication_form=LoginForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html",next_page="shop:product_list"),name='logout'),


]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove')

]

shop/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name="shop"
urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail')

]

shop/models.py
from django.urls import reverse
from django.db import models

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)


    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural="categories"
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])



class Product(models.Model):
    category=models.ForeignKey(Category,related_name='products',
                            on_delete=models.CASCADE)
    
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d',blank=True)

    destcription=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        index_together=(('id','slug'),)

    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id,self.slug])  

shop/views.py
from django.shortcuts import render,get_list_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm

# Create your views here.

def product_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter(available=True)
    if category_slug:
        category=get_list_or_404(Category,slug=category_slug)
        #print(category[0])
        products=products.filter(category=category[0])
    return render(request,'shop/product/list.html',
            {
                "catergory":category,
                "categories":categories,
                "products":products
            }
            )

def product_detail(request,id,slug):
    product=get_list_or_404(Product,id=id,slug=slug,available=True)
    product=product[0]
    #print(product[0].price)
    cart_product_form=CartAddProductForm()
    return render(request,'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>E-Shop </title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static "css/style.min.css" %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'shop:product_list'%}" >
        <strong class="blue-text">Home</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        
        <ul class="navbar-nav mr-auto">
        {% if request.user.is_active %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'accounts:logout'%}" >Logout</a>
            </li>
        
            <li class="nav-item">
              <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
                >Free download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" >Free
                tutorials</a>
            </li>

        {% else %}
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'accounts:login'%}" >Login</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'accounts:register'%}" >Sign Up</a>
              </li> 
              
        {% endif %}      
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            <a href="{% url "cart:cart_detail" %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1">  

                   {{ total_items }}

              </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
            {% endif %}
            {% endwith %}
          </li>
          <li class="nav-item">
            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>MDB GitHub
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
<div id="content">
{% block content%}


{% endblock %}

</div>

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "js/bootstrap.min.js"%}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>